env: "local" #local, dev, prod
database_dsn: "C:/Users/Shyywie/url-shorter-REST-API/storage/storage.db"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "myuser"
  password: "mypassword"